### ISSUE TITLE
update instructions

### ISSUE THREAD

**Issue by htpata** [testmachine-ai/github-action#6]
Change (.sol) for contract and fix typos

**Comment by testmachineprod** [comment]
@htpata @o-hill 

Should we add the hardhat and foundry yml files, so that projects can easily see how to integrate TM in their CI regardless of what framework they're using?

I am hoping to record a quick demo of how to use TM through the CI for both projects. What do you think?

**Comment by htpata** [comment]
I vote yes, but, instead of adding the yaml file here, just add a link to an example repository that has a yaml file (with public dummy contract files) that can be viewed as a reference.   We already have one for term finance but that is private.

**Comment by testmachineprod** [comment]
Good point, 

I can create both dummy repos to showcase this and then record videos on Loom for the documentation for Oct 1st. 

They would have to be placed on the Testmachine github but I know that we don't want to create so many repos.

What do you say @o-hill
